services:
  ca-db:
    container_name: ca-db
    image: postgres
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - PG_DATA=/data/postgres
    volumes:
      - ca-db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - ca-db
    restart: unless-stopped

  ca-api:
    container_name: ca-api
    image: maven:3.8.3-openjdk-17
    working_dir: /home/java/app
    restart: always
    command: mvn spring-boot:run -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    volumes:
      - ./:/home/java/app
    ports: 
      - ${SERVER_PORT}:${SERVER_PORT}
      - "5005:5005"
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_SECURE=${MINIO_SECURE}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
      - TZ=America/Sao_Paulo
    networks:
      - ca-db
    depends_on:
      - ca-db

networks:
  ca-db:
    driver: bridge

volumes:
  ca-db: