INSERT INTO permission (description) values ('access_dash');
INSERT INTO permission (description) values ('access_form');
INSERT INTO permission (description) values ('read_dash');
INSERT INTO permission (description) values ('read_form');
INSERT INTO permission (description) values ('delete_dash');
INSERT INTO permission (description) values ('delete_form');
INSERT INTO permission (description) values ('update_dash');
INSERT INTO permission (description) values ('update_form');

INSERT INTO USERS (email, inclusion_date, name, password, username, role) values ('marcelonavarro11md@gmail.com', now(), 'Marcelo Falchi', '$2a$10$Iu9s/vE3UT4SMlwuLN1tyuxkmV.TqEGEC93Knrfcm5SXYThnDuU1i', 'falchi', 1);
INSERT INTO USERS (email, inclusion_date, name, password, username, role) values ('erickborges@gmail.com', now(), 'Erick Borges', '$2a$10$Iu9s/vE3UT4SMlwuLN1tyuxkmV.TqEGEC93Knrfcm5SXYThnDuU1i', 'erick', 1);
INSERT INTO USERS (email, inclusion_date, name, password, username, role) values ('pegoras@gmail.com', now(), 'Marco Pegoraro', '$2a$10$Iu9s/vE3UT4SMlwuLN1tyuxkmV.TqEGEC93Knrfcm5SXYThnDuU1i', 'pegoraro', 1);
INSERT INTO USERS (email, inclusion_date, name, password, username, role) values ('vini@gmail.com', now(), 'Vini Braun', '$2a$10$Iu9s/vE3UT4SMlwuLN1tyuxkmV.TqEGEC93Knrfcm5SXYThnDuU1i', 'vini_braun', 1);
INSERT INTO USERS (email, inclusion_date, name, password, username, role) values ('menozzo@gmail.com', now(), 'Guilherme Minozzi', '$2a$10$Iu9s/vE3UT4SMlwuLN1tyuxkmV.TqEGEC93Knrfcm5SXYThnDuU1i', 'menozzo', 1);
INSERT INTO USERS (email, inclusion_date, name, password, username, role) values ('leomoreno@gmail.com', now(), 'Leonardo Moreno', '$2a$10$Iu9s/vE3UT4SMlwuLN1tyuxkmV.TqEGEC93Knrfcm5SXYThnDuU1i', 'leo_moreno', 1);
INSERT INTO USERS (email, inclusion_date, name, password, username, role) values ('pegorini@gmail.com', now(), 'Vini Pegorini', '$2a$10$Iu9s/vE3UT4SMlwuLN1tyuxkmV.TqEGEC93Knrfcm5SXYThnDuU1i', 'pegorini', 0);
INSERT INTO USERS (email, inclusion_date, name, password, username, role) values ('marcotoninho@gmail.com', now(), 'Marco Antonio', '$2a$10$Iu9s/vE3UT4SMlwuLN1tyuxkmV.TqEGEC93Knrfcm5SXYThnDuU1i', 'toninho', 1);
INSERT INTO USERS (email, inclusion_date, name, password, username, role) values ('fernanda@gmail.com', now(), 'Fernanda', '$2a$10$Iu9s/vE3UT4SMlwuLN1tyuxkmV.TqEGEC93Knrfcm5SXYThnDuU1i', 'fernanda', 1);
INSERT INTO USERS  (email, inclusion_date, name, password, username, role) values ('cathula@gmail.com', now(), 'Cathula', '$2a$10$Iu9s/vE3UT4SMlwuLN1tyuxkmV.TqEGEC93Knrfcm5SXYThnDuU1i', 'cathula', 1);

insert into user_authorities (tb_user_id, authority_id) values (1,1);
insert into user_authorities (tb_user_id, authority_id) values (1,2);
insert into user_authorities (tb_user_id, authority_id) values (1,3);
insert into user_authorities (tb_user_id, authority_id) values (1,4);
insert into user_authorities (tb_user_id, authority_id) values (1,5);
insert into user_authorities (tb_user_id, authority_id) values (1,6);
insert into user_authorities (tb_user_id, authority_id) values (1,7);
insert into user_authorities (tb_user_id, authority_id) values (1,8);
insert into user_authorities (tb_user_id, authority_id) values (4,1);
insert into user_authorities (tb_user_id, authority_id) values (4,2);
insert into user_authorities (tb_user_id, authority_id) values (4,3);
insert into user_authorities (tb_user_id, authority_id) values (4,4);
insert into user_authorities (tb_user_id, authority_id) values (4,5);
insert into user_authorities (tb_user_id, authority_id) values (4,6);
insert into user_authorities (tb_user_id, authority_id) values (4,7);
insert into user_authorities (tb_user_id, authority_id) values (4,8);